version: '3.8'
services:
  mongo-db:
    image: mongo:latest
    container_name: 'mongo'
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ductruong
      - MONGO_INITDB_ROOT_PASSWORD=ductruong
      - MONGO_INITDB_DATABASE=demodb
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  dbdata:
